export const asusLaptops = [
  {
    id: 1,
    brand: "ASUS",
    model: "ASUS TUF FX608JPR-RV045W",
    series: "TUF Gaming",
    color: "Jaeger Gray",
    year: 2025,
    price: 1449,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/f3/ba/a9/f3baa9e8d56f028693a235fc28f5dea2.jpg",
    specs: {
      cpu: "Intel Core i7-14650HX",
      cores: 16,
      maxSpeed: "5.2 GHz",
      ram: "16GB DDR5-5600",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "1920x1200",
        type: "FHD+ IPS",
        refreshRate: "165Hz",
        features: ["G-SYNC", "MUX Switch"],
      },
      gpu: "NVIDIA RTX 5070 8GB",
      keyboard: "RGB Light",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: [
      "BackPack",
      "Mouse",
      "Mouse pad",
      "Headset",
      "Cleaning kit",
      "Cooling Fan",
      "Laptop Stand",
      "Screen protection",
    ],
  },
  {
    id: 2,
    brand: "ASUS",
    model: "ASUS TUF FX507ZC4",
    series: "TUF Gaming",
    color: "Eclipse Gray",
    year: 2024,
    price: 1299,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/f3/ba/a9/f3baa9e8d56f028693a235fc28f5dea2.jpg",
    specs: {
      cpu: "Intel Core i7-12700H",
      cores: 14,
      maxSpeed: "4.7 GHz",
      ram: "16GB DDR5-4800",
      storage: "512GB PCIe 4.0 NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "144Hz",
        features: ["Adaptive Sync"],
      },
      gpu: "NVIDIA RTX 4050 6GB",
      keyboard: "RGB Light",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["BackPack", "Mouse", "Mouse pad", "Cleaning kit"],
  },
  {
    id: 3,
    brand: "ASUS",
    model: "ASUS ROG Strix G16",
    series: "ROG",
    color: "Original Black",
    year: 2025,
    price: 1899,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/33/dd/0e/33dd0e618581cb7372b50194bdecff3f.jpg",
    specs: {
      cpu: "Intel Core i9-14900HX",
      cores: 24,
      maxSpeed: "5.8 GHz",
      ram: "32GB DDR5-5600",
      storage: "2TB PCIe 4.0 NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "2560x1600",
        type: "QHD+ IPS",
        refreshRate: "240Hz",
        features: ["G-SYNC", "MUX Switch", "Dolby Vision"],
      },
      gpu: "NVIDIA RTX 5080 12GB",
      keyboard: "Per-Key RGB",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: [
      "BackPack",
      "Mouse",
      "Mouse pad",
      "Headset",
      "Cooling Fan",
      "Laptop Stand",
    ],
  },
  {
    id: 4,
    brand: "ASUS",
    model: "ASUS Vivobook Pro 15",
    series: "Vivobook",
    color: "Cool Silver",
    year: 2024,
    price: 899,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/ff/2a/c0/ff2ac029ca9b43d4f47455f28bb73cbd.jpg",
    specs: {
      cpu: "Intel Core i5-13500H",
      cores: 12,
      maxSpeed: "4.7 GHz",
      ram: "16GB DDR4-3200",
      storage: "512GB PCIe 3.0 NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "60Hz",
        features: ["Anti-glare"],
      },
      gpu: "NVIDIA RTX 3050 4GB",
      keyboard: "White Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["BackPack", "Mouse", "Mouse pad"],
  },
  {
    id: 5,
    brand: "ASUS",
    model: "ASUS ZenBook 14",
    series: "ZenBook",
    color: "Pine Grey",
    year: 2025,
    price: 1199,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/d3/ce/d6/d3ced6e0dafe31d32d490bb6763a6f28.jpg",
    specs: {
      cpu: "Intel Core Ultra 7 155H",
      cores: 16,
      maxSpeed: "4.8 GHz",
      ram: "16GB LPDDR5X-7467",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "14 inch",
        resolution: "2880x1800",
        type: "OLED",
        refreshRate: "120Hz",
        features: ["Touchscreen", "Pantone Validated"],
      },
      gpu: "Intel Arc Graphics",
      keyboard: "White Backlit",
    },

    warranty: "2 Years",
    originalBox: true,

    freeItems: ["Sleeve", "Mouse", "USB-C Hub"],
  },
  {
    id: 6,
    brand: "ASUS",
    model: "ASUS TUF Dash F15",
    series: "TUF Gaming",
    color: "Moonlight White",
    year: 2024,
    price: 1099,
    inStock: false,
    image:
      "https://i.pinimg.com/736x/f3/ba/a9/f3baa9e8d56f028693a235fc28f5dea2.jpg",
    specs: {
      cpu: "Intel Core i7-13620H",
      cores: 10,
      maxSpeed: "4.9 GHz",
      ram: "16GB DDR5-4800",
      storage: "512GB PCIe 4.0 NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "144Hz",
        features: ["Adaptive Sync"],
      },
      gpu: "NVIDIA RTX 4060 8GB",
      keyboard: "RGB Light",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["BackPack", "Mouse", "Mouse pad", "Cleaning kit"],
  },
  {
    id: 7,
    brand: "ASUS",
    model: "ASUS ROG Zephyrus G14",
    series: "ROG",
    color: "Moonlight White",
    year: 2025,
    price: 1699,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/1a/8f/1e/1a8f1e7d66960c0315430a2e7d22c594.jpg",
    specs: {
      cpu: "AMD Ryzen 9 8945HS",
      cores: 8,
      maxSpeed: "5.2 GHz",
      ram: "32GB LPDDR5X-7500",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "14 inch",
        resolution: "2560x1600",
        type: "QHD+ OLED",
        refreshRate: "120Hz",
        features: ["G-SYNC", "Pantone Validated"],
      },
      gpu: "NVIDIA RTX 5070 8GB",
      keyboard: "Per-Key RGB",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["BackPack", "Mouse", "Mouse pad", "Headset", "Cooling Fan"],
  },
  {
    id: 8,
    brand: "ASUS",

    model: "ASUS Vivobook S 15",
    series: "Vivobook",
    color: "Indie Black",
    year: 2025,
    price: 799,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/6c/40/33/6c40334bf731f424bd1e7cdfe7ec88a5.jpg",
    specs: {
      cpu: "Intel Core Ultra 5 125H",
      cores: 14,
      maxSpeed: "4.5 GHz",
      ram: "16GB LPDDR5X-7467",
      storage: "512GB PCIe 4.0 NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "1920x1080",
        type: "FHD OLED",
        refreshRate: "60Hz",
        features: ["Touchscreen"],
      },
      gpu: "Intel Arc Graphics",
      keyboard: "White Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Sleeve", "Mouse"],
  },
  {
    id: 9,
    brand: "ASUS",
    model: "ASUS ROG Flow X13",
    series: "ROG",
    color: "Off Black",
    year: 2024,
    price: 1599,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/e5/7a/84/e57a845c4e9efbccf2e7d5f8475ba0e4.jpg",
    specs: {
      cpu: "AMD Ryzen 9 7940HS",
      cores: 8,
      maxSpeed: "5.2 GHz",
      ram: "32GB LPDDR5-6400",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "13.4 inch",
        resolution: "1920x1200",
        type: "FHD+ IPS",
        refreshRate: "165Hz",
        features: ["Touchscreen", "360° Hinge"],
      },
      gpu: "NVIDIA RTX 4060 8GB",
      keyboard: "White Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Stylus", "Sleeve", "Mouse"],
  },
  {
    id: 10,
    brand: "ASUS",


    model: "ASUS TUF Gaming A15",
    series: "TUF Gaming",
    color: "Mecha Gray",
    year: 2024,
    price: 949,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/f3/ba/a9/f3baa9e8d56f028693a235fc28f5dea2.jpg",
    specs: {
      cpu: "AMD Ryzen 7 7735HS",
      cores: 8,
      maxSpeed: "4.75 GHz",
      ram: "16GB DDR5-4800",
      storage: "512GB PCIe 4.0 NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "144Hz",
        features: ["Adaptive Sync"],
      },
      gpu: "NVIDIA RTX 4050 6GB",
      keyboard: "RGB Light",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["BackPack", "Mouse", "Mouse pad", "Cleaning kit"],
  },
  {
    id: 11,
    brand: "Dell",
    model: "Dell G15 5530",
    series: "Gaming",
    color: "Dark Shadow Gray",
    year: 2024,
    price: 1399,
    inStock: true,
    image:
      "https://1pc.co.il/images/thumbs/0162840_-dell-g15-5530-156-in-rd33-15431_510.jpeg",
    specs: {
      cpu: "Intel Core i7-13650HX",
      cores: 14,
      maxSpeed: "4.9 GHz",
      ram: "16GB DDR5",
      storage: "1TB PCIe NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "165Hz",
        features: ["G-SYNC"],
      },
      gpu: "NVIDIA RTX 4060 8GB",
      keyboard: "RGB Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Backpack", "Mouse", "Mouse Pad"],
  },
  {
    id: 12,
    brand: "Dell",
    model: "Dell G16 7630",
    series: "Gaming",
    color: "Obsidian Black",
    year: 2024,
    price: 1599,
    inStock: true,
    image: "https://m.media-amazon.com/images/I/71IV0S6EC8L.jpg",
    specs: {
      cpu: "Intel Core i9-13900HX",
      cores: 24,
      maxSpeed: "5.4 GHz",
      ram: "32GB DDR5",
      storage: "1TB PCIe NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "2560x1600",
        type: "QHD+ IPS",
        refreshRate: "240Hz",
        features: ["G-SYNC"],
      },
      gpu: "NVIDIA RTX 4070 8GB",
      keyboard: "RGB Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Backpack", "Mouse", "Cooling Pad"],
  },
  {
    id: 13,
    brand: "Dell",
    model: "Dell Alienware m16 R2",
    series: "Alienware",
    color: "Lunar Silver",
    year: 2025,
    price: 2499,
    inStock: true,
    image:
      "https://i.gadgets360cdn.com/products/large/Dell-Alienware-m16-R2-DB-709x800-1712664217.jpg",
    specs: {
      cpu: "Intel Core Ultra 9 185H",
      cores: 16,
      maxSpeed: "5.1 GHz",
      ram: "32GB LPDDR5X",
      storage: "2TB PCIe 4.0 NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "2560x1600",
        type: "QHD+ IPS",
        refreshRate: "240Hz",
        features: ["G-SYNC", "Advanced Optimus"],
      },
      gpu: "NVIDIA RTX 4080 12GB",
      keyboard: "AlienFX RGB",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Alienware Backpack", "Mouse", "Headset"],
  },
  {
    id: 14,
    brand: "Dell",
    model: "Dell Alienware x16 R2",
    series: "Alienware",
    color: "Dark Metallic Moon",
    year: 2025,
    price: 2799,
    inStock: false,
    image:
      "https://uaetechdubai.ae/wp-content/uploads/2023/10/Dell_Alienware_x16_R2_Gaming_Laptop_01.png",
    specs: {
      cpu: "Intel Core Ultra 9 185H",
      cores: 16,
      maxSpeed: "5.1 GHz",
      ram: "32GB LPDDR5X",
      storage: "2TB NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "2560x1600",
        type: "QHD+ IPS",
        refreshRate: "240Hz",
        features: ["G-SYNC"],
      },
      gpu: "NVIDIA RTX 4090 16GB",
      keyboard: "Per-Key RGB",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Gaming Backpack", "Mouse", "Cooling Pad"],
  },
  {
    id: 15,
    brand: "Dell",
    model: "Dell Inspiron 16 Plus 7630",
    series: "Inspiron",
    color: "Platinum Silver",
    year: 2024,
    price: 1199,
    inStock: true,

    image: "https://m.media-amazon.com/images/I/51FhQDkkWmL.jpg",
    specs: {
      cpu: "Intel Core i7-13700H",
      cores: 14,
      maxSpeed: "5.0 GHz",
      ram: "16GB DDR5",
      storage: "1TB NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "3072x1920",
        type: "3K IPS",
        refreshRate: "120Hz",
        features: ["Dolby Vision"],
      },
      gpu: "NVIDIA RTX 4050 6GB",
      keyboard: "Backlit",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: ["Laptop Sleeve", "Mouse"],
  },
  {
    id: 16,
    brand: "Dell",
    model: "Dell XPS 13 Plus 9320",
    series: "XPS",
    color: "Graphite",
    year: 2024,
    price: 1699,
    inStock: true,
    image:
      "https://fahavicomputers.co.ke/wp-content/uploads/2024/10/DELL-XPS-13-9320.jpg",
    specs: {
      cpu: "Intel Core i7-1360P",
      cores: 12,
      maxSpeed: "5.0 GHz",
      ram: "16GB LPDDR5",
      storage: "1TB NVMe SSD",
      display: {
        size: "13.4 inch",
        resolution: "3840x2400",

        type: "OLED",
        refreshRate: "60Hz",
        features: ["Touch", "Dolby Vision"],
      },
      gpu: "Intel Iris Xe",
      keyboard: "Backlit",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: ["USB-C Hub"],
  },
  {
    id: 17,
    brand: "Dell",
    model: "Dell XPS 15 9530",
    series: "XPS",
    color: "Silver",
    year: 2024,
    price: 1999,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/3d/84/34/3d8434fe4635e3a95a11541a29f29343.jpg",
    specs: {
      cpu: "Intel Core i9-13900H",
      cores: 14,
      maxSpeed: "5.4 GHz",
      ram: "32GB DDR5",
      storage: "1TB NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "3840x2400",
        type: "OLED",
        refreshRate: "60Hz",
        features: ["Touch"],
      },
      gpu: "NVIDIA RTX 4070 8GB",
      keyboard: "Backlit",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: ["Laptop Sleeve"],
  },
  {
    id: 18,
    brand: "Dell",
    model: "Dell Latitude 7440",
    series: "Latitude",
    color: "Carbon Black",
    year: 2024,
    price: 1249,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/1b/9b/46/1b9b46843bc221f1edc45396fe50c031.jpg",
    specs: {
      cpu: "Intel Core i7-1365U",
      cores: 10,
      maxSpeed: "5.2 GHz",
      ram: "16GB LPDDR5",
      storage: "512GB NVMe SSD",
      display: {
        size: "14 inch",
        resolution: "1920x1200",
        type: "FHD+ IPS",
        refreshRate: "60Hz",
        features: ["Anti-Glare"],
      },
      gpu: "Intel Iris Xe",
      keyboard: "Backlit",
    },
    warranty: "3 Years",
    originalBox: true,
    freeItems: ["Laptop Bag", "Mouse"],
  },
  {
    id: 19,
    brand: "Dell",
    model: "Dell Latitude 5540",
    series: "Latitude",
    color: "Gray",
    year: 2024,
    price: 1099,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/f1/cc/2e/f1cc2eea6e2aefe01d0251be6e226f7b.jpg",
    specs: {
      cpu: "Intel Core i5-1345U",
      cores: 10,
      maxSpeed: "4.7 GHz",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "60Hz",
        features: ["Anti-Glare"],
      },
      gpu: "Intel Iris Xe",
      keyboard: "Backlit",
    },
    warranty: "3 Years",
    originalBox: true,
    freeItems: ["Laptop Bag"],
  },
  {
    id: 20,
    brand: "Dell",
    model: "Dell Vostro 5630",
    series: "Vostro",
    color: "Titan Gray",
    year: 2024,
    price: 899,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/38/f9/cb/38f9cb78a9e052db485d83f8662aa981.jpg",
    specs: {
      cpu: "Intel Core i5-13500H",
      cores: 12,
      maxSpeed: "4.7 GHz",
      ram: "16GB DDR5",
      storage: "512GB NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "1920x1200",
        type: "FHD+ IPS",
        refreshRate: "60Hz",
        features: ["ComfortView"],
      },
      gpu: "Intel Iris Xe",

      keyboard: "Backlit",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: ["Mouse", "Laptop Sleeve"],
  },
  {
    id: 21,
    brand: "Lenovo",
    model: "Lenovo Legion Pro 7i Gen 9",
    series: "Legion",
    color: "Onyx Grey",
    year: 2025,
    price: 2299,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/17/96/5e/17965e8e20317941c7c52ea577973dc6.jpg",
    specs: {
      cpu: "Intel Core i9-14900HX",
      cores: 24,
      maxSpeed: "5.8 GHz",
      ram: "32GB DDR5-5600",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "2560x1600",
        type: "WQXGA IPS",
        refreshRate: "240Hz",
        features: ["G-SYNC", "100% sRGB", "500 nits"],
      },
      gpu: "NVIDIA RTX 5080 16GB",
      keyboard: "RGB Per-Key",
    },
    warranty: "3 Years",
    originalBox: true,
    freeItems: [
      "Gaming Backpack",
      "Legion Mouse",
      "RGB Mouse pad",
      "Gaming Headset",
      "Cleaning kit",
      "Cooling Pad",
      "Laptop Stand",
      "Screen Protector",
    ],
  },
  {
    id: 22,
    brand: "Lenovo",
    model: "Lenovo Legion 5 Pro Gen 9",
    series: "Legion",
    color: "Storm Grey",
    year: 2025,
    price: 1699,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/92/5f/b2/925fb2adfcedea32edb93abd23a33eac.jpg",
    specs: {
      cpu: "AMD Ryzen 9 8945HS",
      cores: 8,
      maxSpeed: "5.2 GHz",
      ram: "16GB DDR5-5600",
      storage: "512GB PCIe 4.0 NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "2560x1600",
        type: "WQXGA IPS",
        refreshRate: "165Hz",
        features: ["FreeSync", "100% sRGB", "500 nits"],
      },
      gpu: "NVIDIA RTX 5070 8GB",
      keyboard: "RGB 4-Zone",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: [
      "Backpack",
      "Mouse",
      "Mouse pad",
      "Headset",
      "Cleaning kit",
      "Cooling Pad",
    ],
  },
  {
    id: 23,
    brand: "Lenovo",
    model: "Lenovo ThinkPad X1 Carbon Gen 12",
    series: "ThinkPad",
    color: "Thunder Black",
    year: 2025,
    price: 1899,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/48/77/75/487775058201d64d7a5394eb0ea5f1a6.jpg",
    specs: {
      cpu: "Intel Core Ultra 7 155H",
      cores: 16,
      maxSpeed: "4.8 GHz",
      ram: "32GB LPDDR5X-7467",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "14 inch",
        resolution: "2880x1800",
        type: "OLED",
        refreshRate: "60Hz",
        features: ["Touch", "100% DCI-P3", "400 nits", "Dolby Vision"],
      },
      gpu: "Intel Arc Graphics",
      keyboard: "Backlit",
    },
    warranty: "3 Years",
    originalBox: true,
    freeItems: [
      "Premium Leather Sleeve",
      "Wireless Mouse",
      "USB-C Hub",
      "Cleaning kit",
      "Privacy Screen",
    ],
  },
  {
    id: 24,
    brand: "Lenovo",
    model: "Lenovo Yoga 9i Gen 9",
    series: "Yoga",
    color: "Tidal Teal",
    year: 2025,
    price: 1599,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/a7/d1/33/a7d133fe17cb20373e4f08506d76437a.jpg",
    specs: {
      cpu: "Intel Core Ultra 7 155H",
      cores: 16,
      maxSpeed: "4.8 GHz",
      ram: "16GB LPDDR5X-7467",
      storage: "512GB PCIe 4.0 NVMe SSD",
      display: {
        size: "14 inch",
        resolution: "2880x1800",
        type: "OLED Touch",
        refreshRate: "90Hz",
        features: ["360° Hinge", "100% DCI-P3", "400 nits", "Stylus Support"],
      },
      gpu: "Intel Arc Graphics",
      keyboard: "Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: [
      "Active Pen",
      "Laptop Sleeve",
      "Wireless Mouse",
      "Cleaning kit",
      "USB-C Adapter",
    ],
  },
  {
    id: 25,
    brand: "Lenovo",
    model: "Lenovo IdeaPad Gaming 3 Gen 8",
    series: "IdeaPad",
    color: "Shadow Black",
    year: 2025,
    price: 899,
    inStock: true,
    image:

      "https://p1-ofp.static.pub/medias/23498737439_Gaming315ACH6_202104301141091678812765875.png",
    specs: {
      cpu: "AMD Ryzen 5 7535HS",
      cores: 6,
      maxSpeed: "4.5 GHz",
      ram: "8GB DDR5-4800",
      storage: "512GB PCIe 3.0 NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "144Hz",
        features: ["FreeSync", "300 nits"],
      },
      gpu: "NVIDIA RTX 4050 6GB",
      keyboard: "Blue Backlit",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: ["Backpack", "Mouse", "Mouse pad", "Cleaning kit"],
  },
  {
    id: 26,
    brand: "Lenovo",
    model: "Lenovo ThinkBook 16 Gen 7",
    series: "ThinkBook",
    color: "Arctic Grey",
    year: 2025,
    price: 1199,
    inStock: false,
    image:
      "https://p4-ofp.static.pub//fes/cms/2024/07/17/nlp7hjbit9r7qbqb941hykxjino4f3761364.png",
    specs: {
      cpu: "Intel Core Ultra 5 125H",
      cores: 14,
      maxSpeed: "4.5 GHz",
      ram: "16GB DDR5-5200",
      storage: "512GB PCIe 4.0 NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "1920x1200",
        type: "WUXGA IPS",
        refreshRate: "60Hz",
        features: ["Anti-glare", "300 nits", "100% sRGB"],
      },
      gpu: "Intel Arc Graphics",
      keyboard: "Backlit",
    },

    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Laptop Bag", "Wireless Mouse", "Cleaning kit", "USB-C Dock"],
  },
  {
    id: 27,
    brand: "Lenovo",
    model: "Lenovo LOQ 15IRX9",
    series: "LOQ",
    color: "Luna Grey",
    year: 2025,
    price: 1099,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/53/fe/4a/53fe4ad0e47583184754c9b23c072dff.jpg",
    specs: {
      cpu: "Intel Core i5-13450HX",
      cores: 10,
      maxSpeed: "4.6 GHz",
      ram: "12GB DDR5-4800",
      storage: "512GB PCIe 4.0 NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "144Hz",
        features: ["G-SYNC", "300 nits"],
      },
      gpu: "NVIDIA RTX 4060 8GB",
      keyboard: "White Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: [
      "Gaming Backpack",
      "Mouse",
      "Mouse pad",
      "Headset",
      "Cleaning kit",
    ],
  },
  {
    id: 28,
    brand: "Lenovo",
    model: "Lenovo Slim 7i Gen 9",
    series: "Slim",
    color: "Cloud Grey",
    year: 2025,
    price: 1349,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/87/f6/dc/87f6dc3f36cab61a99e7ed9b003f9548.jpg",
    specs: {
      cpu: "Intel Core Ultra 7 155H",
      cores: 16,
      maxSpeed: "4.8 GHz",
      ram: "16GB LPDDR5X-7467",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "14 inch",
        resolution: "2880x1800",
        type: "OLED",
        refreshRate: "90Hz",
        features: ["Touch", "100% DCI-P3", "400 nits", "TÜV Low Blue Light"],
      },
      gpu: "Intel Arc Graphics",
      keyboard: "Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: [
      "Premium Sleeve",
      "Wireless Mouse",
      "Cleaning kit",
      "USB-C Hub",
    ],
  },
  {
    id: 29,
    brand: "Lenovo",
    model: "Lenovo Legion Slim 5 Gen 9",
    series: "Legion",
    color: "Storm Grey",
    year: 2025,
    price: 1549,
    inStock: true,
    image:
      "https://dngcorp.vn/wp-content/uploads/2025/04/Laptop-Lenovo-Legion-Pro-5-16IRX9-83DF0046VN_ava1.png",
    specs: {
      cpu: "AMD Ryzen 7 8845HS",
      cores: 8,
      maxSpeed: "5.1 GHz",
      ram: "16GB DDR5-5600",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "2560x1600",
        type: "WQXGA IPS",
        refreshRate: "165Hz",
        features: ["FreeSync", "100% sRGB", "500 nits", "G-SYNC Compatible"],
      },
      gpu: "NVIDIA RTX 5060 8GB",
      keyboard: "RGB 4-Zone",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: [
      "Gaming Backpack",
      "Mouse",
      "RGB Mouse pad",

      "Headset",
      "Cleaning kit",
      "Cooling Pad",
    ],
  },
  {
    id: 30,
    brand: "Lenovo",
    model: "Lenovo IdeaPad Slim 5 Gen 9",
    series: "IdeaPad",
    color: "Abyss Blue",
    year: 2025,
    price: 749,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/25/bf/52/25bf524577e1adb288c889fa97cfe62e.jpg",
    specs: {
      cpu: "AMD Ryzen 5 7530U",
      cores: 6,
      maxSpeed: "4.5 GHz",
      ram: "8GB DDR4-3200",
      storage: "512GB PCIe 3.0 NVMe SSD",
      display: {
        size: "14 inch",
        resolution: "1920x1200",
        type: "WUXGA IPS",
        refreshRate: "60Hz",
        features: ["Anti-glare", "300 nits", "100% sRGB"],
      },
      gpu: "AMD Radeon Graphics",
      keyboard: "Backlit",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: ["Laptop Sleeve", "Wireless Mouse", "Cleaning kit"],
  },
  {
    id: 31,
    brand: "MSI",
    model: "MSI Titan 18 HX A14VIG",
    series: "Titan",
    color: "Core Black",
    year: 2025,
    price: 4299,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/72/b8/29/72b82996601be09a1cb96493dffbac0d.jpg",
    specs: {
      cpu: "Intel Core i9-14900HX",
      cores: 24,
      maxSpeed: "5.8 GHz",
      ram: "128GB DDR5-5600",
      storage: "4TB PCIe 4.0 NVMe SSD",
      display: {
        size: "18 inch",
        resolution: "3840x2400",
        type: "4K UHD+ Mini LED",
        refreshRate: "120Hz",

        features: ["G-SYNC", "100% DCI-P3", "HDR 1000"],
      },
      gpu: "NVIDIA RTX 5090 24GB",
      keyboard: "Per-Key RGB SteelSeries",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: [
      "Gaming Backpack",
      "Gaming Mouse",
      "Mouse pad",
      "Headset",
      "Cooling Pad",
      "Cleaning kit",
    ],
  },
  {
    id: 32,
    brand: "MSI",
    model: "MSI Raider GE78 HX 13VI",
    series: "Raider",
    color: "Star Blue",
    year: 2024,
    price: 3299,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/2a/94/e8/2a94e888bdfb4216bcac2f6c9edd73c3.jpg",
    specs: {
      cpu: "Intel Core i9-13980HX",
      cores: 24,
      maxSpeed: "5.6 GHz",
      ram: "64GB DDR5-5600",
      storage: "2TB PCIe 4.0 NVMe SSD",
      display: {
        size: "17 inch",
        resolution: "2560x1600",
        type: "QHD+ IPS",
        refreshRate: "240Hz",
        features: ["G-SYNC", "100% DCI-P3"],
      },
      gpu: "NVIDIA RTX 4090 16GB",
      keyboard: "Per-Key RGB SteelSeries",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: [
      "Gaming Backpack",
      "Gaming Mouse",
      "Mouse pad",
      "Headset",
      "Cooling Pad",
    ],
  },
  {
    id: 33,
    brand: "MSI",
    model: "MSI Vector GP78 HX 13VG",
    series: "Vector",
    color: "Core Black",
    year: 2024,
    price: 2499,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/2a/49/75/2a497544e0610a907503fd6e522881d4.jpg",
    specs: {
      cpu: "Intel Core i9-13950HX",
      cores: 24,
      maxSpeed: "5.5 GHz",
      ram: "32GB DDR5-5200",
      storage: "2TB PCIe 4.0 NVMe SSD",
      display: {
        size: "17 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "360Hz",
        features: ["G-SYNC"],
      },
      gpu: "NVIDIA RTX 4070 8GB",
      keyboard: "Per-Key RGB SteelSeries",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Gaming Backpack", "Gaming Mouse", "Mouse pad", "Headset"],
  },
  {
    id: 34,
    brand: "MSI",
    model: "MSI Stealth 16 Studio A13VG",
    series: "Stealth",
    color: "Star Blue",
    year: 2024,
    price: 2199,
    inStock: true,
    image:
      "https://asset.msi.com/resize/image/global/product/product_16687515614eeea1b58358a8027ed9421767ef5b02.png62405b38c58fe0f07fcef2367d8a9ba1/600.png",
    specs: {
      cpu: "Intel Core i9-13900H",
      cores: 14,
      maxSpeed: "5.4 GHz",
      ram: "32GB DDR5-5200",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "2560x1600",
        type: "QHD+ IPS",

        refreshRate: "240Hz",
        features: ["G-SYNC", "100% DCI-P3"],
      },
      gpu: "NVIDIA RTX 4070 8GB",
      keyboard: "Per-Key RGB",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Backpack", "Mouse", "Mouse pad", "USB-C Hub"],
  },
  {
    id: 35,
    brand: "MSI",
    model: "MSI Cyborg 15 A13VF",
    series: "Cyborg",
    color: "Translucent Black",
    year: 2024,
    price: 1299,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/09/e4/12/09e412ef4661425e75f8924376e01785.jpg",
    specs: {
      cpu: "Intel Core i7-13620H",
      cores: 10,
      maxSpeed: "4.9 GHz",
      ram: "16GB DDR5-4800",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "144Hz",
        features: ["Adaptive Sync"],
      },
      gpu: "NVIDIA RTX 4060 8GB",
      keyboard: "RGB Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Backpack", "Mouse", "Mouse pad", "Cleaning kit"],
  },
  {
    id: 36,
    brand: "MSI",
    model: "MSI Katana 17 B13VGK",
    series: "Katana",
    color: "Black",
    year: 2024,
    price: 1599,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/1d/82/bf/1d82bf6a34cbbc8c9f7eedd73771245c.jpg",
    specs: {
      cpu: "Intel Core i7-13620H",
      cores: 10,
      maxSpeed: "4.9 GHz",
      ram: "16GB DDR5-4800",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "17.3 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "144Hz",

        features: ["Adaptive Sync"],
      },
      gpu: "NVIDIA RTX 4070 8GB",
      keyboard: "Red Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Gaming Backpack", "Gaming Mouse", "Mouse pad"],
  },
  {
    id: 37,
    brand: "MSI",
    model: "MSI Sword 15 A13VF",
    series: "Sword",
    color: "Black",
    year: 2024,
    price: 1199,
    inStock: true,
    image:
      "https://static.webx.pk/files/17888/Images/-1540-14048-241122082134-17888-0-120123083228421.jpg",
    specs: {
      cpu: "Intel Core i7-13620H",
      cores: 10,
      maxSpeed: "4.9 GHz",
      ram: "16GB DDR5-4800",
      storage: "512GB PCIe 4.0 NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "144Hz",
        features: ["Adaptive Sync"],
      },
      gpu: "NVIDIA RTX 4060 8GB",
      keyboard: "White Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Backpack", "Mouse", "Mouse pad"],
  },
  {
    id: 38,
    brand: "MSI",
    model: "MSI Pulse 17 B13VGK",
    series: "Pulse",
    color: "Core Black",
    year: 2024,
    price: 1799,
    inStock: false,
    image:
      "https://static-media.laptopoutlet.co.uk/catalog/product/1/6/16c37b148fb36c88c0f2f27bfc287690.jpg?height=650",
    specs: {
      cpu: "Intel Core i9-13900H",
      cores: 14,
      maxSpeed: "5.4 GHz",
      ram: "32GB DDR5-5200",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "17 inch",
        resolution: "2560x1600",
        type: "QHD+ IPS",
        refreshRate: "240Hz",
        features: ["G-SYNC", "100% DCI-P3"],
      },
      gpu: "NVIDIA RTX 4070 8GB",
      keyboard: "RGB Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Gaming Backpack", "Gaming Mouse", "Mouse pad", "Headset"],
  },
  {
    id: 39,
    brand: "MSI",
    model: "MSI Crosshair 16 HX D14VFKG",
    series: "Crosshair",
    color: "Moon White",
    year: 2025,
    price: 2099,
    inStock: true,
    image:
      "https://www.creatus.com.bd/image/cache/catalog/MSI/msi-crosshair-16-hx-d14vfkg-core-i7-14th-gen-gaming-laptop-500x500.png.webp",
    specs: {
      cpu: "Intel Core i7-14700HX",
      cores: 20,
      maxSpeed: "5.5 GHz",
      ram: "32GB DDR5-5600",
      storage: "1TB PCIe 4.0 NVMe SSD",
      display: {
        size: "16 inch",
        resolution: "2560x1600",
        type: "QHD+ IPS",

        refreshRate: "240Hz",
        features: ["G-SYNC"],
      },
      gpu: "NVIDIA RTX 5060 8GB",
      keyboard: "Per-Key RGB",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: [
      "Gaming Backpack",
      "Gaming Mouse",
      "Mouse pad",
      "Headset",
      "Cooling Pad",
    ],
  },
  {
    id: 40,
    brand: "MSI",
    model: "MSI Bravo 15 C7VFK",
    series: "Bravo",
    color: "Black",
    year: 2024,
    price: 1099,
    inStock: true,
    image:
      "https://assets.umart.com.au/newsite/images/202403/source_img/MSI-Laptops-MSI-Bravo-15-C7VFK-15-6in-FHD-144Hz-R5-7535HS-RTX-4060-512GB-SSD-16GB-RAM-W11H-Gaming-Laptop-Black-Bravo-15-C7VFK-081AU-19.jpg",
    specs: {
      cpu: "AMD Ryzen 7 7735HS",
      cores: 8,
      maxSpeed: "4.75 GHz",
      ram: "16GB DDR5-4800",
      storage: "512GB PCIe 4.0 NVMe SSD",
      display: {
        size: "15.6 inch",
        resolution: "1920x1080",
        type: "FHD IPS",
        refreshRate: "144Hz",
        features: ["FreeSync Premium"],
      },
      gpu: "AMD Radeon RX 7600M XT 8GB",
      keyboard: "Red Backlit",
    },
    warranty: "2 Years",
    originalBox: true,
    freeItems: ["Backpack", "Mouse", "Mouse pad"],
  },
  {
    id: 41,
    brand: "MacBook",
    model: "MacBook Pro 16-inch M4 Max",
    series: "MacBook Pro",
    color: "Space Black",
    year: 2025,
    price: 3499,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/cc/38/48/cc3848a2541c91ecb971f757d2db10ba.jpg",
    specs: {
      cpu: "Apple M4 Max",
      cores: 16,
      maxSpeed: "4.5 GHz",
      ram: "48GB Unified Memory",
      storage: "1TB SSD",
      display: {
        size: "16.2 inch",
        resolution: "3456x2234",

        type: "Liquid Retina XDR",
        refreshRate: "120Hz",
        features: ["ProMotion", "1600 nits peak", "P3 Wide Color", "True Tone"],
      },
      gpu: "40-Core GPU",
      keyboard: "Backlit Magic Keyboard",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: [
      "USB-C Charging Cable",
      "140W USB-C Power Adapter",
      "Cleaning Cloth",
      "Apple Stickers",
    ],
  },
  {
    id: 42,
    brand: "MacBook",
    model: "MacBook Pro 14-inch M4 Pro",
    series: "MacBook Pro",
    color: "Silver",
    year: 2025,
    price: 2499,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/ae/5b/d8/ae5bd8c71421a17ca832c4c5bc18a0d3.jpg",
    specs: {
      cpu: "Apple M4 Pro",
      cores: 14,
      maxSpeed: "4.4 GHz",
      ram: "24GB Unified Memory",
      storage: "512GB SSD",
      display: {
        size: "14.2 inch",
        resolution: "3024x1964",
        type: "Liquid Retina XDR",
        refreshRate: "120Hz",
        features: ["ProMotion", "1600 nits peak", "P3 Wide Color", "True Tone"],
      },
      gpu: "20-Core GPU",
      keyboard: "Backlit Magic Keyboard",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: [
      "USB-C Charging Cable",
      "96W USB-C Power Adapter",
      "Cleaning Cloth",
      "Apple Stickers",
    ],
  },
  {
    id: 43,
    brand: "MacBook",
    model: "MacBook Air 15-inch M4",
    series: "MacBook Air",
    color: "Midnight",
    year: 2025,
    price: 1499,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/cc/38/48/cc3848a2541c91ecb971f757d2db10ba.jpg",
    specs: {
      cpu: "Apple M4",
      cores: 10,
      maxSpeed: "4.1 GHz",
      ram: "16GB Unified Memory",
      storage: "512GB SSD",
      display: {
        size: "15.3 inch",
        resolution: "2880x1864",
        type: "Liquid Retina",
        refreshRate: "60Hz",
        features: ["500 nits brightness", "P3 Wide Color", "True Tone"],
      },
      gpu: "10-Core GPU",
      keyboard: "Backlit Magic Keyboard",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: [
      "USB-C Charging Cable",
      "35W Dual USB-C Power Adapter",
      "Cleaning Cloth",
      "Apple Stickers",
    ],
  },
  {
    id: 44,
    brand: "MacBook",
    model: "MacBook Air 13-inch M4",
    series: "MacBook Air",
    color: "Starlight",
    year: 2025,

    price: 1299,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/37/1b/51/371b5155fe34fb8cc76b3ebe96609bd4.jpg",
    specs: {
      cpu: "Apple M4",
      cores: 10,
      maxSpeed: "4.1 GHz",
      ram: "16GB Unified Memory",
      storage: "512GB SSD",
      display: {
        size: "13.6 inch",
        resolution: "2560x1664",
        type: "Liquid Retina",
        refreshRate: "60Hz",
        features: ["500 nits brightness", "P3 Wide Color", "True Tone"],
      },
      gpu: "10-Core GPU",
      keyboard: "Backlit Magic Keyboard",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: [
      "USB-C Charging Cable",
      "30W USB-C Power Adapter",
      "Cleaning Cloth",
      "Apple Stickers",
    ],
  },
  {
    id: 45,
    brand: "MacBook",
    model: "MacBook Pro 16-inch M4 Pro",
    series: "MacBook Pro",
    color: "Space Black",
    year: 2025,
    price: 2899,
    inStock: true,
    image:
      "https://i.pinimg.com/1200x/cc/38/48/cc3848a2541c91ecb971f757d2db10ba.jpg",
    specs: {
      cpu: "Apple M4 Pro",
      cores: 14,
      maxSpeed: "4.4 GHz",
      ram: "36GB Unified Memory",
      storage: "1TB SSD",
      display: {
        size: "16.2 inch",
        resolution: "3456x2234",
        type: "Liquid Retina XDR",
        refreshRate: "120Hz",
        features: ["ProMotion", "1600 nits peak", "P3 Wide Color", "True Tone"],
      },
      gpu: "20-Core GPU",
      keyboard: "Backlit Magic Keyboard",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: [
      "USB-C Charging Cable",
      "140W USB-C Power Adapter",
      "Cleaning Cloth",
      "Apple Stickers",
    ],
  },
  {
    id: 46,
    brand: "MacBook",
    model: "MacBook Air 15-inch M3",
    series: "MacBook Air",
    color: "Space Gray",
    year: 2024,
    price: 1299,

    inStock: false,
    image:
      "https://i.pinimg.com/736x/37/1b/51/371b5155fe34fb8cc76b3ebe96609bd4.jpg",
    specs: {
      cpu: "Apple M3",
      cores: 8,
      maxSpeed: "4.0 GHz",
      ram: "8GB Unified Memory",
      storage: "256GB SSD",
      display: {
        size: "15.3 inch",
        resolution: "2880x1864",
        type: "Liquid Retina",
        refreshRate: "60Hz",
        features: ["500 nits brightness", "P3 Wide Color", "True Tone"],
      },
      gpu: "10-Core GPU",
      keyboard: "Backlit Magic Keyboard",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: [
      "USB-C Charging Cable",
      "35W Dual USB-C Power Adapter",
      "Cleaning Cloth",
      "Apple Stickers",
    ],
  },
  {
    id: 47,
    brand: "MacBook",
    model: "MacBook Pro 14-inch M4 Max",
    series: "MacBook Pro",
    color: "Silver",
    year: 2025,
    price: 3199,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/ae/5b/d8/ae5bd8c71421a17ca832c4c5bc18a0d3.jpg",
    specs: {
      cpu: "Apple M4 Max",
      cores: 16,
      maxSpeed: "4.5 GHz",
      ram: "36GB Unified Memory",
      storage: "1TB SSD",
      display: {
        size: "14.2 inch",
        resolution: "3024x1964",
        type: "Liquid Retina XDR",
        refreshRate: "120Hz",
        features: ["ProMotion", "1600 nits peak", "P3 Wide Color", "True Tone"],
      },
      gpu: "40-Core GPU",
      keyboard: "Backlit Magic Keyboard",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: [
      "USB-C Charging Cable",
      "96W USB-C Power Adapter",
      "Cleaning Cloth",
      "Apple Stickers",
    ],
  },
  {
    id: 48,
    brand: "MacBook",
    model: "MacBook Air 13-inch M3",
    series: "MacBook Air",
    color: "Midnight",
    year: 2024,
    price: 1099,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/37/1b/51/371b5155fe34fb8cc76b3ebe96609bd4.jpg",
    specs: {
      cpu: "Apple M3",
      cores: 8,
      maxSpeed: "4.0 GHz",
      ram: "8GB Unified Memory",
      storage: "256GB SSD",
      display: {
        size: "13.6 inch",
        resolution: "2560x1664",
        type: "Liquid Retina",
        refreshRate: "60Hz",
        features: ["500 nits brightness", "P3 Wide Color", "True Tone"],

      },
      gpu: "8-Core GPU",
      keyboard: "Backlit Magic Keyboard",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: [
      "USB-C Charging Cable",
      "30W USB-C Power Adapter",
      "Cleaning Cloth",
      "Apple Stickers",
    ],
  },
  {
    id: 49,
    brand: "MacBook",
    model: "MacBook Pro 14-inch M4",
    series: "MacBook Pro",
    color: "Space Black",
    year: 2025,
    price: 1999,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/ae/5b/d8/ae5bd8c71421a17ca832c4c5bc18a0d3.jpg",
    specs: {
      cpu: "Apple M4",
      cores: 10,
      maxSpeed: "4.1 GHz",
      ram: "16GB Unified Memory",
      storage: "512GB SSD",
      display: {
        size: "14.2 inch",
        resolution: "3024x1964",
        type: "Liquid Retina XDR",
        refreshRate: "120Hz",
        features: ["ProMotion", "1600 nits peak", "P3 Wide Color", "True Tone"],
      },
      gpu: "10-Core GPU",
      keyboard: "Backlit Magic Keyboard",
    },
    warranty: "1 Year",
    originalBox: true,
    freeItems: [
      "USB-C Charging Cable",
      "70W USB-C Power Adapter",
      "Cleaning Cloth",
      "Apple Stickers",
    ],
  },
  {
    id: 50,
    brand: "MacBook",
    model: "MacBook Air 13-inch M4",
    series: "MacBook Air",
    color: "Silver",
    year: 2025,
    price: 1099,
    inStock: true,
    image:
      "https://i.pinimg.com/736x/37/1b/51/371b5155fe34fb8cc76b3ebe96609bd4.jpg",
    specs: {
      cpu: "Apple M4",
      cores: 10,
      maxSpeed: "4.1 GHz",
      ram: "8GB Unified Memory",
      storage: "256GB SSD",
      display: {
        size: "13.6 inch",
        resolution: "2560x1664",
        type: "Liquid Retina",
        refreshRate: "60Hz",
        features: ["500 nits brightness", "P3 Wide Color", "True Tone"],
      },
      gpu: "8-Core GPU",
      keyboard: "Backlit Magic Keyboard",
    },
    warranty: "1 Year",

    originalBox: true,
    freeItems: [
      "USB-C Charging Cable",
      "30W USB-C Power Adapter",
      "Cleaning Cloth",
      "Apple Stickers",
    ],
  },
];

export default asusLaptops;
